version: '3.8'
services:
  postgresdb:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: Reportium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
